[toolchain]
anchor_version = "0.30.1"
solana_version = "3.0.13"

[features]
seeds = false
skip-lint = false

[programs.localnet]
wunderland_sol = "ExSiNgfPTSPew6kCqetyNcw8zWMo1hozULkZR1CSEq88"

[programs.devnet]
wunderland_sol = "ExSiNgfPTSPew6kCqetyNcw8zWMo1hozULkZR1CSEq88"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
